events {}

http {
  upstream users_api { server users-api:4000; }
  upstream farms_api { server farms-api:4001; }
  upstream orders_api { server orders-api:4002; }
  upstream grafana_ui { server grafana:3000; }
  upstream web_ui { server web:80; }

  server {
    listen 80;
    server_name _;

    location /api/users/ {
      rewrite ^/api/users/(.*) /$1 break;
      proxy_pass http://users_api;
      proxy_set_header Host $host;
    }

    location /api/farms/ {
      rewrite ^/api/farms/(.*) /$1 break;
      proxy_pass http://farms_api;
      proxy_set_header Host $host;
    }

    location /api/orders/ {
      rewrite ^/api/orders/(.*) /$1 break;
      proxy_pass http://orders_api;
      proxy_set_header Host $host;
    }

    location /grafana/ {
      proxy_pass http://grafana_ui/;
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://web_ui;
      proxy_set_header Host $host;
    }
  }
}
